window.COMPANIES = [
  { name: "腾讯", aliases: ["Tencent", "腾讯控股"], industry: "互联网", cities: ["深圳", "北京", "上海", "广州", "成都"], careerUrl: "https://careers.tencent.com/" },
  { name: "阿里巴巴", aliases: ["阿里", "Alibaba"], industry: "互联网", cities: ["杭州", "北京", "上海", "深圳", "广州"], careerUrl: "https://talent.alibaba.com/" },
  { name: "字节跳动", aliases: ["ByteDance", "抖音", "今日头条"], industry: "互联网", cities: ["北京", "上海", "深圳", "杭州", "广州"], careerUrl: "https://jobs.bytedance.com/" },
  { name: "美团", aliases: ["Meituan"], industry: "互联网", cities: ["北京", "上海", "深圳", "成都"], careerUrl: "https://zhaopin.meituan.com/" },
  { name: "京东", aliases: ["JD", "京东集团"], industry: "电商", cities: ["北京", "上海", "深圳", "成都"], careerUrl: "https://zhaopin.jd.com/" },
  { name: "百度", aliases: ["Baidu"], industry: "互联网", cities: ["北京", "上海", "深圳", "广州"], careerUrl: "https://talent.baidu.com/" },
  { name: "网易", aliases: ["NetEase"], industry: "互联网", cities: ["杭州", "广州", "北京", "上海"], careerUrl: "https://hr.163.com/" },
  { name: "小米", aliases: ["Xiaomi", "小米集团"], industry: "硬件互联网", cities: ["北京", "武汉", "南京", "上海", "深圳"], careerUrl: "https://hr.xiaomi.com/" },
  { name: "快手", aliases: ["Kuaishou"], industry: "互联网", cities: ["北京", "上海", "深圳", "杭州"], careerUrl: "https://zhaopin.kuaishou.cn/" },
  { name: "拼多多", aliases: ["PDD"], industry: "电商", cities: ["上海", "广州", "深圳"], careerUrl: "https://careers.pinduoduo.com/" },
  { name: "滴滴", aliases: ["DiDi", "滴滴出行"], industry: "出行", cities: ["北京", "杭州", "上海"], careerUrl: "https://talent.didiglobal.com/" },
  { name: "携程", aliases: ["Trip.com", "携程集团"], industry: "旅游", cities: ["上海", "北京", "南通"], careerUrl: "https://careers.trip.com/" },
  { name: "哔哩哔哩", aliases: ["B站", "bilibili"], industry: "内容社区", cities: ["上海", "北京", "杭州"], careerUrl: "https://jobs.bilibili.com/" },
  { name: "知乎", aliases: ["Zhihu"], industry: "内容社区", cities: ["北京", "上海", "成都"], careerUrl: "https://www.zhihu.com/careers" },
  { name: "微博", aliases: ["新浪微博", "Weibo"], industry: "内容社区", cities: ["北京", "上海"], careerUrl: "https://career.sina.com.cn/" },
  { name: "搜狐", aliases: ["Sohu"], industry: "互联网", cities: ["北京"], careerUrl: "https://hr.sohu.com/" },
  { name: "360", aliases: ["三六零", "奇虎360"], industry: "网络安全", cities: ["北京", "上海", "成都"], careerUrl: "https://hr.360.cn/" },
  { name: "爱奇艺", aliases: ["iQIYI"], industry: "视频娱乐", cities: ["北京", "上海"], careerUrl: "https://careers.iqiyi.com/campus/" },
  { name: "去哪儿", aliases: ["Qunar"], industry: "旅游", cities: ["北京"], careerUrl: "https://qunar.zhiye.com/" },
  { name: "得物", aliases: ["毒App", "Poizon"], industry: "电商", cities: ["上海", "杭州"], careerUrl: "https://campus.dewu.com/578078/" },
  { name: "华为", aliases: ["Huawei", "华为技术"], industry: "通信科技", cities: ["深圳", "上海", "北京", "杭州", "南京", "成都", "西安", "武汉"], careerUrl: "https://career.huawei.com/" },
  { name: "商汤科技", aliases: ["SenseTime"], industry: "人工智能", cities: ["上海", "北京", "深圳", "杭州"], careerUrl: "https://www.sensetime.com/cn/join-index" },
  { name: "旷视科技", aliases: ["Megvii"], industry: "人工智能", cities: ["北京", "上海"], careerUrl: "https://www.megvii.com/join-us" },
  { name: "科大讯飞", aliases: ["iFLYTEK"], industry: "人工智能", cities: ["合肥", "北京", "上海", "广州"], careerUrl: "https://job.iflytek.com/" },
  { name: "第四范式", aliases: ["4Paradigm"], industry: "人工智能", cities: ["北京", "上海", "深圳"], careerUrl: "https://www.4paradigm.com/careers" },
  { name: "云从科技", aliases: ["CloudWalk"], industry: "人工智能", cities: ["广州", "上海", "北京"], careerUrl: "https://www.cloudwalk.com/careers" },
  { name: "寒武纪", aliases: ["Cambricon"], industry: "AI芯片", cities: ["北京", "上海", "南京"], careerUrl: "https://www.cambricon.com/careers" },
  { name: "地平线", aliases: ["Horizon Robotics"], industry: "自动驾驶芯片", cities: ["北京", "上海", "南京"], careerUrl: "https://horizon.ai/careers" },
  { name: "阿里云", aliases: ["Alibaba Cloud"], industry: "云计算", cities: ["杭州", "北京", "上海", "深圳"], careerUrl: "https://talent.alibaba.com/" },
  { name: "腾讯云", aliases: ["Tencent Cloud"], industry: "云计算", cities: ["深圳", "北京", "上海", "广州"], careerUrl: "https://careers.tencent.com/" },
  { name: "火山引擎", aliases: ["Volcengine"], industry: "云计算", cities: ["北京", "上海", "深圳", "杭州"], careerUrl: "https://jobs.bytedance.com/" },
  { name: "金山云", aliases: ["Kingsoft Cloud"], industry: "云计算", cities: ["北京", "武汉", "珠海"], careerUrl: "https://www.ksyun.com/career" },
  { name: "UCloud", aliases: ["优刻得"], industry: "云计算", cities: ["上海", "北京", "深圳"], careerUrl: "https://www.ucloud.cn/site/careers.html" },
  { name: "用友", aliases: ["Yonyou"], industry: "企业服务", cities: ["北京", "上海", "深圳", "南京"], careerUrl: "https://career.yonyou.com/" },
  { name: "金蝶", aliases: ["Kingdee"], industry: "企业服务", cities: ["深圳", "上海", "北京"], careerUrl: "https://career.kingdee.com/" },
  { name: "明源云", aliases: ["Ming Yuan Cloud"], industry: "企业服务", cities: ["深圳", "武汉", "北京"], careerUrl: "https://www.mingyuanyun.com/careers" },
  { name: "纷享销客", aliases: ["FXiaoke"], industry: "企业服务", cities: ["北京", "上海", "深圳"], careerUrl: "https://www.fxiaoke.com/careers" },
  { name: "销售易", aliases: ["Xiaoshouyi", "Neocrm"], industry: "企业服务", cities: ["北京", "上海", "深圳"], careerUrl: "https://www.xiaoshouyi.com/about/join" },
  { name: "蚂蚁集团", aliases: ["Ant Group", "支付宝"], industry: "金融科技", cities: ["杭州", "上海", "北京", "深圳"], careerUrl: "https://talent.antgroup.com/" },
  { name: "陆金所", aliases: ["Lufax"], industry: "金融科技", cities: ["上海", "深圳"], careerUrl: "https://www.lufaxholding.com/careers" },
  { name: "京东科技", aliases: ["JD Technology"], industry: "金融科技", cities: ["北京", "南京", "成都"], careerUrl: "https://zhaopin.jd.com/" },
  { name: "度小满", aliases: ["Du Xiaoman"], industry: "金融科技", cities: ["北京", "上海", "重庆"], careerUrl: "https://www.duxiaoman.com/joinus" },
  { name: "招银网络科技", aliases: ["招银网科"], industry: "银行科技", cities: ["深圳", "杭州", "成都"], careerUrl: "https://cmbntjob.cmbchina.com/" },
  { name: "平安科技", aliases: ["Ping An Technology"], industry: "金融科技", cities: ["深圳", "上海", "成都"], careerUrl: "https://talent.pingan.com/" },
  { name: "兴业数金", aliases: ["兴业数字金融"], industry: "银行科技", cities: ["上海", "福州", "成都"], careerUrl: "https://www.cibfintech.com/" },
  { name: "建信金科", aliases: ["建信金融科技"], industry: "银行科技", cities: ["北京", "上海", "深圳", "武汉"], careerUrl: "https://job.ccbft.com/" },
  { name: "工银科技", aliases: ["工银金融科技"], industry: "银行科技", cities: ["北京", "上海", "广州"], careerUrl: "https://job.icbc.com.cn/" },
  { name: "中银金科", aliases: ["中银金融科技"], industry: "银行科技", cities: ["上海", "北京", "深圳"], careerUrl: "https://campus.chinahr.com/pages/bocfintech" },
  { name: "农银金科", aliases: ["农银金融科技"], industry: "银行科技", cities: ["北京", "上海", "广州"], careerUrl: "https://job.abchina.com/" },
  { name: "交银金科", aliases: ["交银金融科技"], industry: "银行科技", cities: ["上海", "北京", "深圳"], careerUrl: "https://job.bankcomm.com/" },
  { name: "招商银行", aliases: ["CMB"], industry: "银行", cities: ["深圳", "上海", "北京", "杭州"], careerUrl: "https://career.cmbchina.com/" },
  { name: "平安银行", aliases: ["PAB"], industry: "银行", cities: ["深圳", "上海", "北京"], careerUrl: "https://bank.pingan.com/about/career/" },
  { name: "微众银行", aliases: ["WeBank"], industry: "银行", cities: ["深圳"], careerUrl: "https://www.webank.com/careers" },
  { name: "网商银行", aliases: ["MYbank"], industry: "银行", cities: ["杭州", "上海"], careerUrl: "https://talent.antgroup.com/" },
  { name: "同花顺", aliases: ["Hithink"], industry: "金融信息", cities: ["杭州"], careerUrl: "https://job.10jqka.com.cn/" },
  { name: "东方财富", aliases: ["Eastmoney"], industry: "金融信息", cities: ["上海"], careerUrl: "https://about.eastmoney.com/careers" },
  { name: "恒生电子", aliases: ["Hundsun"], industry: "金融软件", cities: ["杭州", "上海", "深圳"], careerUrl: "https://campus.hundsun.com/" },
  { name: "大智慧", aliases: ["DZH"], industry: "金融信息", cities: ["上海"], careerUrl: "https://www.gw.com.cn/career" },
  { name: "比亚迪", aliases: ["BYD"], industry: "新能源车", cities: ["深圳", "西安", "长沙", "合肥", "济南"], careerUrl: "https://job.byd.com/" },
  { name: "蔚来", aliases: ["NIO"], industry: "新能源车", cities: ["上海", "合肥", "北京"], careerUrl: "https://nio.jobs.feishu.cn/" },
  { name: "小鹏汽车", aliases: ["XPeng"], industry: "新能源车", cities: ["广州", "北京", "上海"], careerUrl: "https://xiaopeng.jobs.feishu.cn/" },
  { name: "理想汽车", aliases: ["Li Auto"], industry: "新能源车", cities: ["北京", "上海", "常州"], careerUrl: "https://www.lixiang.com/careers" },
  { name: "零跑汽车", aliases: ["Leapmotor"], industry: "新能源车", cities: ["杭州", "金华"], careerUrl: "https://www.leapmotor.com/join" },
  { name: "极氪", aliases: ["Zeekr"], industry: "新能源车", cities: ["杭州", "宁波", "上海"], careerUrl: "https://zeekr.jobs.feishu.cn/" },
  { name: "广汽埃安", aliases: ["AION"], industry: "新能源车", cities: ["广州", "上海"], careerUrl: "https://www.aion.com.cn/career" },
  { name: "上汽集团", aliases: ["SAIC"], industry: "汽车", cities: ["上海", "南京", "郑州"], careerUrl: "https://saicmotor.zhiye.com/" },
  { name: "长城汽车", aliases: ["GWM"], industry: "汽车", cities: ["保定", "上海", "北京"], careerUrl: "https://career.gwm.com.cn/" },
  { name: "吉利汽车", aliases: ["Geely"], industry: "汽车", cities: ["杭州", "宁波", "上海"], careerUrl: "https://campus.geely.com/" },
  { name: "宁德时代", aliases: ["CATL"], industry: "新能源", cities: ["宁德", "上海", "厦门", "成都"], careerUrl: "https://www.catl.com/careers/" },
  { name: "欣旺达", aliases: ["Sunwoda"], industry: "新能源", cities: ["深圳", "惠州", "南京"], careerUrl: "https://www.sunwoda.com/career" },
  { name: "亿纬锂能", aliases: ["EVE Energy"], industry: "新能源", cities: ["惠州", "武汉", "成都"], careerUrl: "https://www.evebattery.com/career" },
  { name: "国轩高科", aliases: ["Gotion"], industry: "新能源", cities: ["合肥", "南京", "上海"], careerUrl: "https://www.gotion.com.cn/career" },
  { name: "阳光电源", aliases: ["Sungrow"], industry: "新能源", cities: ["合肥", "上海", "深圳"], careerUrl: "https://career.sungrowpower.com/" },
  { name: "隆基绿能", aliases: ["LONGi"], industry: "新能源", cities: ["西安", "上海"], careerUrl: "https://www.longi.com/cn/join-us/" },
  { name: "天合光能", aliases: ["Trina Solar"], industry: "新能源", cities: ["常州", "上海"], careerUrl: "https://www.trinasolar.com/cn/careers" },
  { name: "晶科能源", aliases: ["JinkoSolar"], industry: "新能源", cities: ["上海", "上饶", "嘉兴"], careerUrl: "https://www.jinkosolar.com/cn/site/careers" },
  { name: "远景能源", aliases: ["Envision"], industry: "新能源", cities: ["上海", "无锡", "北京"], careerUrl: "https://www.envision-group.com/cn/careers.html" },
  { name: "特斯拉中国", aliases: ["Tesla China", "特斯拉"], industry: "新能源车", cities: ["上海", "北京", "深圳"], careerUrl: "https://www.tesla.cn/careers" },
  { name: "中芯国际", aliases: ["SMIC"], industry: "半导体", cities: ["上海", "北京", "深圳", "天津"], careerUrl: "https://www.smics.com/cn/site/careers" },
  { name: "华虹半导体", aliases: ["Hua Hong"], industry: "半导体", cities: ["上海", "无锡"], careerUrl: "https://www.huahonggrace.com/cn/careers" },
  { name: "韦尔股份", aliases: ["Will Semiconductor"], industry: "半导体", cities: ["上海", "北京", "深圳"], careerUrl: "https://www.willsemi.com/careers" },
  { name: "兆易创新", aliases: ["GigaDevice"], industry: "半导体", cities: ["北京", "上海", "合肥"], careerUrl: "https://www.gigadevice.com/cn/careers/" },
  { name: "紫光展锐", aliases: ["UNISOC"], industry: "半导体", cities: ["上海", "北京", "深圳", "西安"], careerUrl: "https://www.unisoc.com/cn_zh/careers" },
  { name: "海思", aliases: ["HiSilicon"], industry: "半导体", cities: ["深圳", "上海", "北京"], careerUrl: "https://career.huawei.com/" },
  { name: "长江存储", aliases: ["YMTC"], industry: "半导体", cities: ["武汉", "上海"], careerUrl: "https://www.ymtc.com/cn/careers" },
  { name: "长鑫存储", aliases: ["CXMT"], industry: "半导体", cities: ["合肥", "北京", "上海"], careerUrl: "https://www.cxmt.com/careers" },
  { name: "闻泰科技", aliases: ["Wingtech"], industry: "半导体制造", cities: ["上海", "深圳", "嘉兴", "无锡"], careerUrl: "https://www.wingtech.com/career" },
  { name: "立讯精密", aliases: ["Luxshare"], industry: "电子制造", cities: ["东莞", "深圳", "苏州"], careerUrl: "https://www.luxshare-ict.com/career" },
  { name: "歌尔股份", aliases: ["Goertek"], industry: "电子制造", cities: ["潍坊", "青岛", "深圳", "上海"], careerUrl: "https://www.goertek.com/careers" },
  { name: "蓝思科技", aliases: ["Lens Technology"], industry: "电子制造", cities: ["长沙", "深圳", "东莞"], careerUrl: "https://www.hnlens.com/career" },
  { name: "大疆", aliases: ["DJI", "大疆创新"], industry: "智能硬件", cities: ["深圳", "上海", "北京", "西安"], careerUrl: "https://we.dji.com/zh-CN" },
  { name: "海康威视", aliases: ["Hikvision"], industry: "智能安防", cities: ["杭州", "武汉", "西安"], careerUrl: "https://campus.hikvision.com/" },
  { name: "大华股份", aliases: ["Dahua"], industry: "智能安防", cities: ["杭州", "西安", "成都"], careerUrl: "https://job.dahuatech.com/" },
  { name: "联想", aliases: ["Lenovo"], industry: "硬件", cities: ["北京", "上海", "深圳", "武汉"], careerUrl: "https://jobs.lenovo.com/" },
  { name: "浪潮", aliases: ["Inspur"], industry: "服务器与云", cities: ["济南", "北京", "上海"], careerUrl: "https://career.inspur.com/" },
  { name: "中兴通讯", aliases: ["ZTE"], industry: "通信", cities: ["深圳", "南京", "上海", "西安"], careerUrl: "https://job.zte.com.cn/" },
  { name: "新华三", aliases: ["H3C"], industry: "网络设备", cities: ["杭州", "北京", "成都"], careerUrl: "https://career.h3c.com/" },
  { name: "富士康", aliases: ["Foxconn", "鸿海"], industry: "电子制造", cities: ["深圳", "郑州", "成都", "太原"], careerUrl: "https://www.foxconn.com.cn/zh-cn/careers" },
  { name: "安克创新", aliases: ["Anker"], industry: "消费电子", cities: ["长沙", "深圳"], careerUrl: "https://www.anker-in.com/cn/careers" },
  { name: "泡泡玛特", aliases: ["POP MART"], industry: "消费零售", cities: ["北京", "上海"], careerUrl: "https://app.mokahr.com/social-recruitment/popmart/" },
  { name: "名创优品", aliases: ["MINISO"], industry: "消费零售", cities: ["广州", "深圳"], careerUrl: "https://www.miniso.com/careers" },
  { name: "元气森林", aliases: ["Genki Forest"], industry: "消费品", cities: ["北京", "上海", "广州"], careerUrl: "https://www.yuanqisenlin.com/career" },
  { name: "农夫山泉", aliases: ["Nongfu Spring"], industry: "消费品", cities: ["杭州", "上海", "北京"], careerUrl: "https://www.nongfuspring.com/careers" },
  { name: "伊利", aliases: ["Yili"], industry: "消费品", cities: ["呼和浩特", "北京", "上海"], careerUrl: "https://career.yili.com/" },
  { name: "蒙牛", aliases: ["Mengniu"], industry: "消费品", cities: ["呼和浩特", "北京", "上海"], careerUrl: "https://career.mengniu.com.cn/" },
  { name: "海尔", aliases: ["Haier"], industry: "家电", cities: ["青岛", "上海", "北京"], careerUrl: "https://maker.haier.net/client/campus" },
  { name: "美的", aliases: ["Midea"], industry: "家电", cities: ["佛山", "广州", "上海"], careerUrl: "https://careers.midea.com/" },
  { name: "格力", aliases: ["Gree"], industry: "家电", cities: ["珠海", "合肥", "武汉"], careerUrl: "https://gree.zhiye.com/" },
  { name: "顺丰", aliases: ["SF Express", "顺丰速运"], industry: "物流", cities: ["深圳", "上海", "北京", "杭州"], careerUrl: "https://hr.sf-express.com/" },
  { name: "菜鸟", aliases: ["Cainiao"], industry: "物流科技", cities: ["杭州", "上海", "深圳"], careerUrl: "https://talent.alibaba.com/" },
  { name: "京东物流", aliases: ["JD Logistics"], industry: "物流科技", cities: ["北京", "上海", "成都"], careerUrl: "https://zhaopin.jd.com/" },
  { name: "三一重工", aliases: ["SANY"], industry: "工程机械", cities: ["长沙", "北京", "上海"], careerUrl: "https://sany.zhiye.com/" },
  { name: "迈瑞医疗", aliases: ["Mindray"], industry: "医疗器械", cities: ["深圳", "武汉", "南京"], careerUrl: "https://career.mindray.com/campus" },
  { name: "药明康德", aliases: ["WuXi AppTec"], industry: "医药研发", cities: ["上海", "苏州", "无锡"], careerUrl: "https://www.wuxiapptec.com/careers" },
  { name: "百济神州", aliases: ["BeiGene"], industry: "生物医药", cities: ["北京", "上海", "广州"], careerUrl: "https://www.beigene.com/careers/" },
  { name: "恒瑞医药", aliases: ["Hengrui"], industry: "医药", cities: ["连云港", "上海", "成都"], careerUrl: "https://www.hrs.com.cn/careers" },
  { name: "复星医药", aliases: ["Fosun Pharma"], industry: "医药", cities: ["上海", "北京", "苏州"], careerUrl: "https://www.fosunpharma.com/careers" },
  { name: "贝壳", aliases: ["KE Holdings", "贝壳找房"], industry: "房产科技", cities: ["北京", "上海", "成都"], careerUrl: "https://join.ke.com/" }
];
